In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

from datetime import datetime

In [2]:
WORK_DIR = 'C:\\Users\\Laevskiy\\Desktop\\05-22\\AC101'

In [3]:
date1 = '2021-11-27 07:00:00'
date2 = '2020-05-13 19:00:00'
date3 = '2020-12-10 07:00:00'
date4 = '2021-01-13 19:00:00'
date5 = '2021-02-14 07:00:00'

In [4]:
chem_in = WORK_DIR + "\\raw data\\!chem баки питания.xlsx"
chem_fe2 = WORK_DIR + "\\raw data\\!chem Fe2+.xlsx"
df_total_ds_1h = WORK_DIR + "\\df_total_ds_1h.zip"

In [5]:
df_chem_in = pd.read_excel(chem_in, header=0, index_col=0, parse_dates=True, usecols="A:G")
df_chem_in = df_chem_in.apply(pd.to_numeric, errors='coerce')
df_chem_in.fillna(0, inplace=True)

In [6]:
min_date = datetime.fromisoformat('2019-01-01 00:00:00')
max_date = datetime.fromisoformat('2021-12-31 17:00:00')

In [7]:
df_chem_in.sort_index()

,320 RC-101 S Fe,320 RC-101 S Sобщ,320 RC-101 S Sso42-,320 RC-101 S As,320 RC-101 S Сорг,320 RC-101 S Собщ
Timestamp,,,,,,
2018-12-01 09:00:00,27.10,25.4,0.0,8.90,0.470,1.340
2018-12-02 09:00:00,25.99,26.9,0.0,7.95,0.500,1.330
2018-12-02 13:00:00,25.78,27.2,0.0,7.95,0.480,1.320
2018-12-02 17:00:00,26.71,26.2,0.0,8.38,0.430,1.220
2018-12-03 01:00:00,29.23,26.1,0.0,9.65,0.570,1.090
...,...,...,...,...,...,...
2022-03-24 19:00:00,24.80,25.4,0.0,5.60,0.220,0.560
2022-03-25 07:00:00,26.70,26.7,0.0,5.90,0.323,0.958
2022-03-25 19:00:00,30.10,26.5,0.0,6.60,0.500,1.290
2022-03-26 07:00:00,28.20,26.4,0.0,6.70,0.497,1.330
2022-03-26 19:00:00,28.80,26.0,0.0,6.85,0.500,1.290

In [8]:
df_chem_in.reset_index(inplace=True)

In [9]:
df_chem_in['Timestamp'] = pd.to_datetime(df_chem_in['Timestamp'].astype(str), errors='coerce')

In [11]:
df_chem_in.dropna(subset=['Timestamp'])

,Timestamp,320 RC-101 S Fe,320 RC-101 S Sобщ,320 RC-101 S Sso42-,320 RC-101 S As,320 RC-101 S Сорг,320 RC-101 S Собщ
0,2018-12-01 09:00:00,27.10,25.4,0.0,8.90,0.470,1.340
1,2018-12-02 09:00:00,25.99,26.9,0.0,7.95,0.500,1.330
2,2018-12-02 13:00:00,25.78,27.2,0.0,7.95,0.480,1.320
3,2018-12-02 17:00:00,26.71,26.2,0.0,8.38,0.430,1.220
4,2018-12-03 20:00:00,0.00,25.9,0.0,8.79,0.640,1.100
...,...,...,...,...,...,...,...
1498,2022-03-24 19:00:00,24.80,25.4,0.0,5.60,0.220,0.560
1499,2022-03-25 07:00:00,26.70,26.7,0.0,5.90,0.323,0.958
1500,2022-03-25 19:00:00,30.10,26.5,0.0,6.60,0.500,1.290
1501,2022-03-26 07:00:00,28.20,26.4,0.0,6.70,0.497,1.330
1502,2022-03-26 19:00:00,28.80,26.0,0.0,6.85,0.500,1.290

In [12]:
df_chem_in = df_chem_in.set_index('Timestamp')

In [13]:
df_chem_in_1h = df_chem_in.resample('H', convention='start').first()

In [14]:
cols = ['Fe', 'Stot', 'SO4', 'As', 'Corg', 'Ctot']
df_chem_in_1h.columns = cols

In [15]:
df_chem_in_1h.replace({0: np.NaN}, inplace=True)

Fe2+

In [16]:
df_chem_fe2 = pd.read_excel(chem_fe2, index_col=0, parse_dates=True, usecols="A:B")
df_chem_fe2 = df_chem_fe2.apply(pd.to_numeric, errors='coerce')
df_chem_fe2.fillna(0, inplace=True)

In [17]:
df_chem_fe2.sort_index()

                     330-ТК-102 L Fe2+
Timestamp
2018-11-29 00:00:00                0.0
2018-11-29 00:00:00                0.0
2018-11-29 01:00:00                0.0
2018-11-29 02:00:00                0.0
2018-11-29 03:00:00                0.0
...                                ...
2022-03-31 19:00:00                0.0
2022-03-31 20:00:00                0.0
2022-03-31 21:00:00                0.0
2022-03-31 22:00:00                0.0
2022-03-31 23:00:00                0.0

[30931 rows x 1 columns]

In [18]:
df_chem_fe2.reset_index(inplace=True)
df_chem_fe2['Timestamp'] = pd.to_datetime(df_chem_fe2['Timestamp'].astype(str), errors='coerce')
df_chem_fe2.dropna(subset=['Timestamp'])

                Timestamp  330-ТК-102 L Fe2+
0     2018-11-29 20:00:00                0.0
1     2018-11-29 21:00:00                0.0
2     2018-11-29 22:00:00                0.0
3     2018-11-29 23:00:00                0.0
4     2018-11-29 00:00:00                0.0
...                   ...                ...
30926 2022-03-31 15:00:00                0.0
30927 2022-03-31 16:00:00                0.0
30928 2022-03-31 17:00:00                0.0
30929 2022-03-31 18:00:00                0.0
30930 2022-03-31 19:00:00                0.0

[30930 rows x 2 columns]

In [19]:
df_chem_fe2 = df_chem_fe2.set_index('Timestamp')

In [20]:
df_chem_fe2_1h = df_chem_fe2.resample('H').first()

In [21]:
df_chem_fe2_1h.fillna(method='ffill', inplace=True)

In [22]:
colsFe = ['Fe2+']
df_chem_fe2_1h.columns = colsFe

In [23]:
df1 = df_chem_in_1h.merge(df_chem_fe2_1h, how='inner', left_index=True, right_index=True)

In [24]:
df1 = df1.drop('SO4', axis=1)

In [25]:
df1['Fe2+'] = df1['Fe2+'].shift(-2)

In [26]:
df1 = df1[df1['Fe'].notna()]

In [27]:
df_total_ds_1h = pd.read_csv(df_total_ds_1h, index_col=0, parse_dates=True)
df_total_ds_1h = df_total_ds_1h.apply(pd.to_numeric, errors='coerce')
df_total_ds_1h.fillna(0, inplace=True)

In [28]:
df_total_ds_1h.describe().T

,count,mean,std,min,25%,50%,75%,max
320PU101,23898.0,14.156005,18.850957,0.000000,0.000000,0.000000,34.204861,50.509444
320PU103,23898.0,8.271072,15.423743,0.000000,0.000000,0.000000,0.000000,49.939444
320RC101DIC02,23898.0,1339.631511,341.381013,988.425903,1001.446777,1354.931436,1657.932955,2035.591939
330AC101FI06,23898.0,8.883433,10.346363,-0.048949,-0.000476,0.034722,19.357085,31.433258
330AC101FI07,23898.0,14.635539,15.552402,0.000000,0.028935,2.582947,30.332177,44.384363
330AC101FI08,23898.0,7.925864,8.467505,0.000000,0.006583,1.012340,17.194997,21.733496
330AC101FI09,23898.0,2.668350,3.116183,0.000000,0.004340,0.004455,5.245622,11.886725
330AC101FI10,23898.0,1.032361,1.537638,-0.002315,-0.001039,0.022010,1.932718,7.638040
330AC101FI51,23898.0,2772.928036,2873.570258,-22.416878,-2.479565,8.726138,5442.148330,7551.899822
330AC101FI52,23898.0,35.145545,37.260594,0.000000,0.039089,3.547419,73.700107,97.323842
330AC101FIC40,23898.0,1.285850,4.474061,-0.007224,0.000000,0.000000,0.000050,25.740942
330AC101FICZ01,23898.0,1087.132059,1149.230298,-9.130833,-1.302067,2.919595,2159.428038,4499.999512
330AC101FICZ02,23898.0,945.729750,998.122927,-15.897170,-0.434016,-0.069465,1910.668783,2705.136918
330AC101FICZ03,23898.0,481.961117,515.911413,-1.291571,-0.591765,-0.450678,962.895437,1598.459443
330AC101FICZ04,23898.0,183.630659,204.188726,-0.496362,-0.037799,0.000000,379.033598,850.337194
330AC101FICZ05,23898.0,74.473996,83.934618,-0.361202,-0.108504,-0.095337,156.965181,499.999939
330AC101LICZ01,23898.0,66.825417,21.353735,-1.294649,65.982800,67.552183,81.150202,102.820295
330AC101LICZ01.1,23898.0,19.804399,27.138408,-1.186343,3.501288,8.653690,25.741303,103.269676
330AC101LICZ01.2,23898.0,18.924203,28.172555,0.000000,0.000000,7.010274,25.000000,100.000000
330AC101PI64,23898.0,16.724140,10.585518,0.000000,0.000000,22.193947,24.759264,27.468582
330AC101PI65,23898.0,4.924532,3.278993,-22.178490,1.165535,6.017897,6.957804,23.657766
330AC101PIC63A,23898.0,20.648667,12.707167,-0.079386,0.314801,27.000004,29.999848,31.283941
330AC101PIC63A.1,23898.0,61.870438,35.509470,0.000000,28.460743,62.413218,100.000000,100.000000
330AC101PIZ61,23898.0,21.133427,12.618405,-0.148051,7.261540,28.199997,29.991071,36.149828
330AC101TIC01,23898.0,150.940364,105.587323,-3.732639,26.002847,216.387819,225.003872,309.982666
330AC101TIC02,23898.0,151.758628,105.810215,-3.819445,25.835807,215.871921,225.000102,309.201295
330AC101TIC03,23898.0,169.823909,101.636165,-3.819445,42.763674,201.481616,225.339875,309.027922
330AC101TIC04,23898.0,173.497090,104.243650,13.182027,39.451258,219.996633,227.103447,309.027922
330AC101TIC05,23898.0,144.313894,102.739153,0.000000,25.288539,186.136795,219.842159,309.690656
330AC101TIZ61,23898.0,167.139891,85.504480,7.659439,34.377187,217.712575,223.998588,230.015428
330PT101PIZ01,23898.0,21.406267,16.476741,-0.078181,0.002050,33.860807,34.179343,39.286185
330TK101LIC01,23898.0,60.822394,32.481469,-1.244293,43.039620,50.611034,101.585245,103.009295
330TK101PI11,23898.0,3.038696,3.098631,-0.251696,0.035285,0.395335,6.190080,9.531492
330TK101TI03,23898.0,107.819081,78.942915,9.797695,29.532910,98.604003,182.691826,308.593750
330TK101TIC02,23898.0,97.207430,68.384928,0.000000,23.717186,99.970339,165.736078,206.423615
330TK102LIC01,23898.0,55.917725,34.433018,-1.302180,39.950834,41.000000,99.756512,102.575266
330TK102PI02,23898.0,0.087563,0.134992,-0.062494,-0.004368,0.062880,0.140778,1.139964
330TK102TIC02,23898.0,64.327958,38.233691,3.986143,23.960764,61.413764,101.749614,206.018509
380HX101FIC01,23898.0,8.166505,16.064411,-0.000764,0.000000,0.000080,0.016226,70.119195
380HX101LIC01,23898.0,55.120757,36.904875,-1.244213,12.090959,45.002994,99.826385,103.298607
380HX101PIC03,23898.0,2.930278,3.087934,-0.438056,0.012960,0.482471,6.000140,9.542646
OXYGEN/OxyPurity,23898.0,76.570074,40.716220,0.000000,95.000000,97.702987,99.900002,100.000000
OXYGEN/OxyPurityB,23898.0,88.227218,31.590850,0.000000,99.400002,99.509694,99.699997,100.000000
Fe,23898.0,1.227277,5.771525,0.000000,0.000000,0.000000,0.000000,47.190000
Stot,23898.0,1.293324,5.720527,0.000000,0.000000,0.000000,0.000000,33.700000
SO4,23898.0,0.004988,0.181595,0.000000,0.000000,0.000000,0.000000,24.400000
As,23898.0,0.361147,1.736573,0.000000,0.000000,0.000000,0.000000,14.500000
Corg,23898.0,0.030207,0.481879,0.000000,0.000000,0.000000,0.000000,71.000000
Ctot,23898.0,0.050443,0.228535,0.000000,0.000000,0.000000,0.000000,2.150000
Fe2+,23898.0,0.648978,1.024680,0.000000,0.000000,0.000000,1.240000,74.400000
D(S),23898.0,250.286467,953.460792,0.000000,0.000000,0.000000,0.000000,4300.000000
D(SL),23898.0,69.474981,332.624366,0.000000,0.000000,0.000000,0.000000,1828.000000

In [29]:
df_total_ds_1h = df_total_ds_1h.drop('SO4', axis=1)

In [30]:
cols1 = ['Fe', 'Stot', 'As', 'Corg', 'Ctot', 'Fe2+']

In [31]:
df_total_ds_1h.sort_index()

,320PU101,320PU103,320RC101DIC02,330AC101FI06,330AC101FI07,330AC101FI08,330AC101FI09,330AC101FI10,330AC101FI51,330AC101FI52,...,OXYGEN/OxyPurity,OXYGEN/OxyPurityB,Fe,Stot,As,Corg,Ctot,Fe2+,D(S),D(SL)
2019-01-01 07:00:00,39.395000,0.000000,1650.615707,18.998168,20.320517,15.469354,1.912728,0.004103,5308.464948,56.703037,...,0.000000,0.000000,0.0,0.0,0.0,0.00,0.00,0.00,3900.0,1600.0
2019-01-01 08:00:00,39.400556,0.000000,1651.312554,18.982688,20.534195,15.498610,2.105368,0.001700,5308.080298,57.120547,...,0.000000,0.000000,0.0,0.0,0.0,0.00,0.00,1.11,0.0,0.0
2019-01-01 09:00:00,39.398333,0.000000,1653.447314,19.088036,20.343886,15.712674,2.305624,0.025356,5307.429711,57.473187,...,0.000000,0.000000,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0
2019-01-01 10:00:00,39.383333,0.000000,1649.847311,18.950787,20.507571,15.410165,1.930532,0.084392,5310.106883,56.887133,...,0.000000,0.000000,0.0,0.0,0.0,0.00,0.00,1.23,0.0,0.0
2019-01-01 11:00:00,39.406111,0.000000,1652.307998,18.859231,20.232325,15.529065,2.205978,0.056138,5313.755440,56.881265,...,0.000000,0.000000,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-01 15:00:00,29.836778,29.849945,1001.737692,17.933112,28.909645,17.441576,5.148100,0.469014,5595.424619,69.903634,...,99.799586,99.599998,0.0,0.0,0.0,0.00,0.00,1.41,0.0,0.0
2021-12-01 16:00:00,29.838445,29.832945,1001.739702,17.944252,28.905124,17.439454,5.147172,0.473691,5600.977732,69.914116,...,99.799864,99.599998,0.0,0.0,0.0,0.00,0.00,1.45,0.0,0.0
2021-12-01 17:00:00,29.838278,29.834112,1001.735683,17.941045,28.909846,17.436548,5.146063,0.468859,5600.835396,69.908254,...,99.797642,99.599998,0.0,0.0,0.0,0.00,0.00,1.52,0.0,0.0
2021-12-01 18:00:00,29.836167,29.835667,1001.734076,17.934824,28.898473,17.431617,5.142922,0.480957,5599.570321,69.889197,...,99.799725,99.599998,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0
2021-12-01 19:00:00,29.831334,29.834112,1001.736889,17.926047,28.914146,17.439165,5.142506,0.473659,5595.807124,69.885932,...,99.797920,99.576166,22.8,23.9,4.3,0.31,0.81,0.00,0.0,0.0

In [32]:
df1.sort_index()

                        Fe  Stot    As   Corg   Ctot  Fe2+
Timestamp
2018-12-01 09:00:00  27.10  25.4  8.90  0.470  1.340  0.00
2018-12-02 09:00:00  25.99  26.9  7.95  0.500  1.330  0.00
2018-12-02 13:00:00  25.78  27.2  7.95  0.480  1.320  0.00
2018-12-02 17:00:00  26.71  26.2  8.38  0.430  1.220  0.00
2018-12-03 01:00:00  29.23  26.1  9.65  0.570  1.090  0.00
...                    ...   ...   ...    ...    ...   ...
2022-03-24 19:00:00  24.80  25.4  5.60  0.220  0.560  1.35
2022-03-25 07:00:00  26.70  26.7  5.90  0.323  0.958  1.68
2022-03-25 19:00:00  30.10  26.5  6.60  0.500  1.290  2.13
2022-03-26 07:00:00  28.20  26.4  6.70  0.497  1.330  2.17
2022-03-26 19:00:00  28.80  26.0  6.85  0.500  1.290   NaN

[1302 rows x 6 columns]

In [33]:
df_total_ds_1h.head()

,320PU101,320PU103,320RC101DIC02,330AC101FI06,330AC101FI07,330AC101FI08,330AC101FI09,330AC101FI10,330AC101FI51,330AC101FI52,...,OXYGEN/OxyPurity,OXYGEN/OxyPurityB,Fe,Stot,As,Corg,Ctot,Fe2+,D(S),D(SL)
2019-01-01 07:00:00,39.395000,0.0,1650.615707,18.998168,20.320517,15.469354,1.912728,0.004103,5308.464948,56.703037,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,3900.0,1600.0
2019-01-01 08:00:00,39.400556,0.0,1651.312554,18.982688,20.534195,15.498610,2.105368,0.001700,5308.080298,57.120547,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.11,0.0,0.0
2019-01-01 09:00:00,39.398333,0.0,1653.447314,19.088036,20.343886,15.712674,2.305624,0.025356,5307.429711,57.473187,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2019-01-01 10:00:00,39.383333,0.0,1649.847311,18.950787,20.507571,15.410165,1.930532,0.084392,5310.106883,56.887133,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.23,0.0,0.0
2019-01-01 11:00:00,39.406111,0.0,1652.307998,18.859231,20.232325,15.529065,2.205978,0.056138,5313.755440,56.881265,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0

In [34]:
df_total_ds_1h.replace({0: np.NaN}, inplace=True)

In [35]:
df_total_ds_1h[cols1]=df_total_ds_1h[cols1].interpolate(method='time')

In [36]:
df_total_ds_1h[cols1].head(100)

,Fe,Stot,As,Corg,Ctot,Fe2+
2019-01-01 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-01 08:00:00,NaN,NaN,NaN,NaN,NaN,1.110000
2019-01-01 09:00:00,NaN,NaN,NaN,NaN,NaN,1.170000
2019-01-01 10:00:00,NaN,NaN,NaN,NaN,NaN,1.230000
2019-01-01 11:00:00,NaN,NaN,NaN,NaN,NaN,1.285000
...,...,...,...,...,...,...
2019-01-05 06:00:00,30.124444,27.471875,11.526944,0.454063,0.999219,1.344024
2019-01-05 07:00:00,30.136296,27.465104,11.529213,0.454115,0.999401,1.347378
2019-01-05 08:00:00,30.148148,27.458333,11.531481,0.454167,0.999583,1.350732
2019-01-05 09:00:00,30.160000,27.451563,11.533750,0.454219,0.999766,1.354085
2019-01-05 10:00:00,30.171852,27.444792,11.536019,0.454271,0.999948,1.357439

In [37]:
df_total_ds_1h = df_total_ds_1h[df_total_ds_1h['Fe'] !=0]

In [44]:
date1=df1.sample()

In [45]:
assert(df1.loc[date1,'Fe'] == df_total_ds_1h.loc[date1, 'Fe'])
assert(df1.loc[date1,'Stot'] == df_total_ds_1h.loc[date1, 'Stot'])
assert(df1.loc[date1,'As'] == df_total_ds_1h.loc[date1, 'As'])
assert(df1.loc[date1,'Corg'] == df_total_ds_1h.loc[date1, 'Corg'])
assert(df1.loc[date1,'Ctot'] == df_total_ds_1h.loc[date1, 'Ctot'])
assert(df1.loc[date1,'Fe2+'] == df_total_ds_1h.loc[date1, 'Fe2+'])

ValueError: Cannot index with multidimensional key

In [39]:
assert(df1.loc[date2,'Fe'] == df_total_ds_1h.loc[date2, 'Fe'])
assert(df1.loc[date2,'Stot'] == df_total_ds_1h.loc[date2, 'Stot'])
assert(df1.loc[date2,'As'] == df_total_ds_1h.loc[date2, 'As'])
assert(df1.loc[date2,'Corg'] == df_total_ds_1h.loc[date2, 'Corg'])
assert(df1.loc[date2,'Ctot'] == df_total_ds_1h.loc[date2, 'Ctot'])
assert(df1.loc[date2,'Fe2+'] == df_total_ds_1h.loc[date2, 'Fe2+'])

In [40]:
assert(df1.loc[date3,'Fe'] == df_total_ds_1h.loc[date3, 'Fe'])
assert(df1.loc[date3,'Stot'] == df_total_ds_1h.loc[date3, 'Stot'])
assert(df1.loc[date3,'As'] == df_total_ds_1h.loc[date3, 'As'])
assert(df1.loc[date3,'Corg'] == df_total_ds_1h.loc[date3, 'Corg'])
assert(df1.loc[date3,'Ctot'] == df_total_ds_1h.loc[date3, 'Ctot'])
assert(df1.loc[date3,'Fe2+'] == df_total_ds_1h.loc[date3, 'Fe2+'])

In [41]:
assert(df1.loc[date4,'Fe'] == df_total_ds_1h.loc[date4, 'Fe'])
assert(df1.loc[date4,'Stot'] == df_total_ds_1h.loc[date4, 'Stot'])
assert(df1.loc[date4,'As'] == df_total_ds_1h.loc[date4, 'As'])
assert(df1.loc[date4,'Corg'] == df_total_ds_1h.loc[date4, 'Corg'])
assert(df1.loc[date4,'Ctot'] == df_total_ds_1h.loc[date4, 'Ctot'])
assert(df1.loc[date4,'Fe2+'] == df_total_ds_1h.loc[date4, 'Fe2+'])

In [43]:
assert(df1.loc[date5,'Fe'] == df_total_ds_1h.loc[date5, 'Fe'])
assert(df1.loc[date5,'Stot'] == df_total_ds_1h.loc[date5, 'Stot'])
assert(df1.loc[date5,'As'] == df_total_ds_1h.loc[date5, 'As'])
assert(df1.loc[date5,'Corg'] == df_total_ds_1h.loc[date5, 'Corg'])
assert(df1.loc[date5,'Ctot'] == df_total_ds_1h.loc[date5, 'Ctot'])
assert(df1.loc[date5,'Fe2+'] == df_total_ds_1h.loc[date5, 'Fe2+'])